global_vars:
  - name: "clipboard"
    type: "clipboard"
  - name: global_var
    type: echo
    params:
      echo: "This is a normal global variable"
  - name: today
    type: date
    params:
      format: "%Y/%m/%d"
  - name: now
    type: date
    params:
      format: "%Y/%m/%d/%H:%M:%S"


matches:
  - trigger: ";global_var"
    replace: "{{global_var}}"
  - trigger: ";date"
    replace: "{{today}}"
  - trigger: ";now"
    replace: "{{now}}"

  - trigger: ";state;focus"
    replace: "{{output}}"
    vars:
      - name: state_focus
        type: echo
        params:
          echo: "$ESPANSO/state/state_focus.txt"
      - name: current_mode
        type: shell
        params:
          cmd: "if [ -f {{state_focus}} ]; then cat {{state_focus}}; else echo '' > {{state_focus}}; echo ''; fi"
      - name: output
        type: shell
        params:
          cmd: |
            if [ "{{current_mode}}" = "WORK" ]; then
              echo "Switched to PERSONAL"
              # Update state to PERSONAL for next time
              echo "PERSONAL" > {{state_focus}}
            elif [ "{{current_mode}}" = "PERSONAL" ]; then
              echo "Switched to WORK"
              # Update state to WORK for next time
              echo "WORK" > {{state_focus}}
            else
              echo "Initializing to WORK"
              echo "WORK" > {{state_focus}}
            fi